export enum ACTIONS {
  CHANGE_APP_TYPE = 'CHANGE_APP_TYPE',
  CLICK_BURGER_MENU = 'CLICK_BURGER_MENU',
  CLOSE_SIDE_MENU = 'CLOSE_SIDE_MENU',
  IS_GAME_START = 'IS_GAME_START',
  RIGHT_ANSWER = 'RIGHT_ANSWER',
  WRONG_ASNWER = 'WRONG_ASNWER',
  CLEAR_ANSWERS = 'CLEAR_ANSWERS',
  ADD_REPEAT_WORDS = 'ADD_REPEAT_WORDS',
  ADD_STATISTIC_DATA = 'ADD_STATISTIC_DATA',
  SORT_DIRECTION = 'SORT_DIRECTION',
  SORT_BY = 'SORT_BY'
}
